# Welcome responses
welcome_message = "*WELCOME TO `clavaChat` WHATSAPP MARKETPLACE*.\nPlease tell us what you would like to do:\n\n1. *General AI Chatbot services* \n2. *Buying and Selling* \n3. *Housing Services* \n4. *clavaChat Library* \n5. *Help* \n\nPlease reply with the number of your choice or type `exit` to exit"
selling_response = "Please tell us what you would like to do:\n\n1. Sell a product\n2. Looking for a product to buy\n3. Exit\n\nPlease reply with the number of your choice or type exit to exit"
buyer_response = "WHAT ARE YOU LOOKING FOR?\nreply with what you are looking for in this form:\n- *Product name* \n- *Condition* \n- *Budget* \n\nYou can consider this example:*iphone13 pro-max 256GB,boxed $1200* \n\nReply with exit to exit."
seller_response = "Please tell us what you would like to do:\n\n1. Add a product\n2. View Your Listings \n3. Subscriptions\n\nPlease reply with the number of your choice or reply with word `exit` to exit"
seller_add_response = "*What are you selling?* \nPlease provide the following details about the product you are selling:\n1.Product\n2.Condition\n3.Price \n\nConsider this example: *iphone13 pro-max 256GB, Boxed $1500* \n\n🚨 _note that after adding your first product, you will be able to just post other products without going through all these steps again!_ \n\nTo exit simply type exit"
welcome_response3 = "Are you a `Landlord` or a `Tenant`?\n\n1. Landlord\n2. Tenant\n3. Exit\n\nPlease reply with the number of your choice or type exit to exit"
welcome_landlord_response = "Please tell us what you would like to do:\n\n1. Add a property\n2. View properties\n3. Subscriptions\n\nPlease reply with the number of your choice or type exit to exit"
add_property_response = "Please provide the following details about the property you would like to add:\n\n1. House information\n2. Location\n3. Rent *needed per month*\n\nConsider this example:\n *1 room with tiles,ceiling and own entrance door* in *Waterfalls Prospect* $130\n\n🚨 _note that after adding your first property, you will be able to just post other properties without going through all these steps again!_ \n\nTo exit simply type exit"
welcome_tenant_response = "Please tell us what you would like to do:\n\n1. View available properties or houses to rent\n2. Exit\n\nPlease *reply* with the number of your choice or type exit to exit"
tenant_response = "Please tell us the type of apartment/house you are looking for and your budget. e.g. 2 bedroom apartment in Sunningdale with tiles and ceiling, budget $300\n\nTo exit simply type exit"
product_added_successfully = "*{}* \nis now added to your listings and everyone looking for a similar product with a close budget ranging from *${} to ${}* can see it.\nHappy selling! `clava` ."
apartment_added_successfully = "This property \n {} \nis now added to your listings,interested people will be given your contact details for viewing and further discussions.\n\nHappy Leasing! `clava` ."
invalid_sale_response =  "⚠️Your product details are invalid.\n\n- Please provide the *product name*, *condition*, and *price* \n\n- Consider this example: *iphone13 pro-max 256GB, Boxed $1500*.\n\n reply with exit to exit."
invalid_house_information ="⚠️Invalid house information. \n\n- Please provide *house description*, *location*, and *your preferd budget*  as per month\n\n- Consider this example: *full house with en-suite* in *Gunhill* *$850* \n\n reply with exit to exit."
landlord_name_response = "We would like to use your name when referring tenants to you.\nPlease provide your Name or Company Name"
no_houses_found_response = "We couldn't find any match based on your need, try another location."
no_products_found_response = "We couldn't find any match based on the product you're looking for,try another one or increase your budget."
invalid_product_information ="⚠️Invalid product information provided. \n\n- Please provide:\n- *Product name* \n- *Condition* \n- *Budget* \n\nYou can consider this example:*iphone13 pro-max 256GB,boxed $1200* \nreply with `exit` to exit."
questions_list =["who are you?", "what is your name", "where are you from", "who made you?", "who is tankan", "tankan"]

library_response = "Welcome to the `clavaChat` Library.\n\n- -> If looking for a novel/book, simply reply with the title of that book/novel.\n- -> If it's a past exam paper, reply with *level*,*paper title*,*year* and the *session* eg:\n- *A level mathematics paper 1 November 2023*.\n- -> For marking schemes, reply with word *solution* ,*level*,*paper title*,*year* and the *session* eg:\n- *solution A level mathematics paper 1 November 2023*.\n *DISCLAIMER* Please `note` that responses may not be accurate!\n\nType `exit` to exit or message 0779586059 for queries."

#subscription section
subs_response_default = "*YOUR FREE TRIAL HAS `EXPIRED`* \nPlease Choose `Subscription` Option\n1. Monthly Subscription\n2. Check Subscription Status\n3. Help\n4. `Exit`\n\n *Please reply with the `number` of your choice*."
subs_response1 = "Monthly Subscription Plan:\n\n *Features* \n1. Unlimited Access Message Requests\n2. 24/7 Customer Support\n3. Cancel Anytime - `guaranteed money back within first week` if you decided to change otherwise.\n\n *Pricing* \n$1/month\n\n To subscribe, please reply with, *Y* to proceed or *N* to abort."
subs_response2 = "Your subscription is on {}"
subs_response3 = f"Your subscription expiry date is. To add a subscription, please reply with *1* to subscribe."
subs_response5 = "Subscription Plans:\n"
subs_response5 += "-Chat Monthly Subscription Plan $1/m ✅\n"
subs_response5 += "-Landlord 3-Months Subscription Plan $4.86/ quarterly ✅\n"
subs_response5 += "-Sellers Monthly Subscription Plan $0.66/m ✅\n"
subs_response5 += "By subscribing To any of the Plan, you will gain unlimited number of messages with clava chatbot and enjoy 24/7 customer support.\n\n"
subs_response5 += "To proceed with the Monthly Subscription Plan,You agree to the clavaChat.termsofservice .\n\n Ts & Cs apply."
subs_response4 = "Thank you for your interest in clavaChat.\n"
subs_response4 += "For any inquiries or assistance, please contact our support team.\n\n `263779586059` or send direct email to `solutions@tphub.com`\n\n"
subs_response4 += "© 2023 TechProjectsHub. All rights reserved.\n"
subs_response_final4=subs_response4
subs_response5 = "Thank you for using our service. If you need any further assistance, please feel free to contact us.\n\nHave a great day!🫰"
subs_payment_agree_response = "Your subscription is being created. You will be billed $1/month. To cancel your subscription, please reply with *2* or reply with your Ecocash mobile number in the form: `07XX` to proceed."
subs_payment_deny_response = "Your subscription request has been cancelled. To subscribe, please reply with *1*."
subs_error_response = "An error occurred. Please try again later."
subs_cancel_response = "Your subscription has been cancelled. To reactivate, please reply with *1* to subscribe."
landlord_subs_response = "Landlord Subscription Plan:\n\n *Features* \n1. Manage all your properties\n2. 24/7 Customer Support\n3. Cancel Anytime - `guaranteed money back within first week` if you decided to change otherwise.\n\n *Pricing List* \n- 1. $5.77/monthly\n- 2. $13.80/quarterly\n- 3. $22.00/half-yearly\n- 4. $39.90/Yearly  \n\n To subscribe, please reply with your subscription choice to proceed or exit to exit."
landlord_proceed_with_subs_response = "Your *{}* subscription is being created. You will be billed $`{}`/month. Please reply with your Ecocash mobile number in the form: `07XX` to proceed.\n\nTo cancel your subscription, please reply with *exit*."
landlord_monthly_subs_response = "Your subscription is on {}"

#Payment section
payment_response_default_response = "You are about to create a Monthly `Subscription` Plan 💳\n\n1. Confirm Subscription \n2. Cancel Subscription\n3. Help\n4. Exit\n\nPlease reply with the number of your choice."
ecocash_number_valid_response = "Please wait for the popup on your phone to confirm the payment.\n\n Once you confirm the payment, send us the transaction sms here on whatsApp\n *DISCLAIMER* _the subscription activation may take up to 1-3 minutes_ .If there is no feedback of `subscription` update from us, please contact support by typing word *help*.\n\n Your subscription will be activated once the payment is confirmed."
ecocash_number_invalid_response = "Invalid Ecocash mobile number. Please reply with your Ecocash mobile number in the form: `07XX` to proceed."
error_response = "An error occured. Please try again later."
eccocash_transaction_success_response = "Your subscription has been successfully activated. Thank you for subscribing to our service. Enjoy!"
transaction_message = "240313.1849.F42721."
reference_number_error_response = "Transaction ID or Reference Number is invalid. Please try again."
pop_reference_number_error_response = "The POP message is invalid, please send the whole message again."
trial_response = " Hi {},Enjoy a happy chat with `clavaChat` \nRegards,\n*clava*."

#housing and selling services
no_listings_response = "You have no listings yet. Please add a product to sell.\n\n1. Add a product\n2. Exit"
not_a_seller_response = "You are not a Registered as a seller!\n1. Contact Support\n2. Exit \n\nPlease reply with the word help or type exit to exit"
no_apartment_listings = "You have no listings yet. Please add a property to rent.\n\n1. Add a property\n2. Exit"
not_a_landlord_response = "You are not a Registered as a landlord!\n1. Contact Support\n2. Exit \n\nPlease reply with the word help or type exit to exit"
after_property_listing_response ="\n- *1* to Add a property\n- *more* to view more properties\n- *exit* to exit\n- *delete* property number. e.g. *delete 1* to delete or *edit 1 price =$300* to edit.\nFor more help reply with *help*"
after_listing_response ="\n- *1* to Add a product\n- *more* to view more\n- *exit* to exit\n- *delete* product number. e.g. *delete 1* to delete or *edit 1 price =$300* to edit.\nFor more help reply with *help*"
after_buyer_listing_response ="\n- *exit* to exit\n- *more* to view more products\nFor more help reply with *help*"
underline_response = "\n______________*REPLY WITH:*______________"
after_tenant_listing_response ="\n- *exit* to exit\n- *more* to view more properties\nFor more help reply with *help*"
buying_selling_help_help = "`clavaChat` *WhatsApp marketplace  support* 🆘\n\nclavaChat connects *buyers* and *sellers*, *tenants* and *landlords*. You can buy or sell products, rent or lease properties\n\n*1. FOR AI CHATBOT SERVICE*\n- choose option 1\n\n2. *FOR LANDLORDS:"
buying_selling_help_help +="*\n*Landlord can post and manage properties, they can edit property information or delete a property*\n- To add a property you go to *housing services* >> select Landlord >> add a property and follow the steps."
buying_selling_help_help +="\n- To edit a property you first go to your property listings tab\n `Once there you can`:\n- edit by typing *edit* and property number and what you want to edit e.g *edit 2 rent = $300*"
buying_selling_help_help+="\n- To delete a property you type: *delete* and property number e.g *delete 1* to remove listing number *1* from your listings or if the property has been occupied.\n\n*3. FOR TENANTS:*\n*Tenants can view available properties*"
buying_selling_help_help+="\n- To view available properties you go to *housing services* >> select Tenant >> view available properties\n\n *4. FOR SELLERS:* \n *Sellers can post and manage products,edit product information or delete a product*"
buying_selling_help_help+= "\n- To add a product you go to *selling* >> select Sell a product >> add a product and follow the steps.\n- To edit a product you first go to your product listings tab\n `Once there you can`:"
buying_selling_help_help+= "\n- edit by typing *edit* and product number and what you want to edit e.g edit 2 price = $300\n- *delete* product number e.g *delete 1* to remove from listings or if the product has been sold or out of stock."
buying_selling_help_help+="\n\n*5. FOR BUYERS:*\n- Buyers can view available products\n- To view available products you go to *selling* >> select Looking for a product to buy\n\n6. *FOR SUBSCRIPTIONS:* \n- To subscribe to our services you go to a service first then *subscriptions* >> select your Subscription choice and follow the steps\n\nType *exit* to exit. or message 0779586059 for support."
buying_selling_help_help_final = buying_selling_help_help